accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accounts.views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path
from receipts.views import (
    ReceiptListView,
    AccountListView,
    ExpenseCategoryListView, 
    AccountCreateView,
    CategoryCreateView,
    ReceiptCreateView,
)



urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("accounts/", AccountListView.as_view(), name="accounts_list"),
    path("categories/", ExpenseCategoryListView.as_view(), name="categories_list"),
    path("accounts/create/", AccountCreateView.as_view(), name="accounts_create"),
    path("categories/create/", CategoryCreateView.as_view(), name="categories_create"),
    path("create/", ReceiptCreateView.as_view(), name="receipts_create"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

# Create your models here.
USER_MODEL = settings.AUTH_USER_MODEL


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(decimal_places=3, max_digits=10)
    tax = models.DecimalField(decimal_places=3, max_digits=10)
    date = models.DateField()
    purchaser = models.ForeignKey(
        USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        "ExpenseCategory",
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    account = models.ForeignKey(
        "Account",
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True,
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username, password=password
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()

    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from receipts.models import Account, ExpenseCategory, Receipt

# Create your views here.


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/categories/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "receipts/accounts/create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("accounts_list")


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receipts/categories/create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("categories_list")


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Expenses</title>
</head>

<body>
    <nav>
        <ul>
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'home' %}">Home</a>
            </li>
            <li>
                <a href="{% url 'logout' %}">Logout</a>
            </li>
            <li>
                <a href="{% url 'categories_create' %}">Create Expense Category</a>
            </li>
            <li>
                <a href="{% url 'categories_list' %}">Expense Categories</a>
            </li>
            <li>
                <a href="{% url 'accounts_create' %}">Create Account</a>
            </li>
            <li>
                <a href="{% url 'accounts_list' %}">Accounts</a>
            </li>
            <li>
                <a href="{% url 'receipts_create' %}">Create Receipt</a>
            </li>
            {% else %}
            <li>
                <a href="{% url 'signup' %}">Sign Up</a>
            </li>
            <li>
                <a href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% block content %}
    {% endblock content %}
</body>

</html>

receipts/templates/receipts/accounts/create.html
{% extends 'base.html' %}

{% block content %}
<main>
    <h2>Create New Receipt Account</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Create Account</button>
    </form>
</main>

{% endblock content %}

receipts/templates/receipts/accounts/list.html
{% extends 'base.html' %}

{% block content %}
<main>
    <h2>Accounts</h2>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Number</th>
                <th>Number of receipts</th>
            </tr>
        </thead>
        <tbody>
            {% for account in account_list %}
            <tr>
                <td>{{ account.name }}</td>
                <td>{{ account.number }}</td>
                <td>{{ account.receipts.all|length }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</main>
{% endblock content %}

receipts/templates/receipts/categories/create.html
{% extends 'base.html' %}

{% block content %}
<main>
    <h2>Create New Expense Category</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Create Expense Category</button>
    </form>
</main>

{% endblock content %}

receipts/templates/receipts/categories/list.html
{% extends 'base.html' %}

{% block content %}
<main>
    <h2>Expense Categories</h2>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Number of receipts</th>
            </tr>
        </thead>
        <tbody>
            {% for category in expensecategory_list %}
            <tr>
                <td>{{ category.name }}</td>
                <td>{{ category.receipts.all|length }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>


</main>
{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}

{% block content %}
<main>
    <h2>Create New Receipt</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Create Receipt</button>
    </form>
</main>

{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}

{% block content %}
<main>
    <h1>Home</h1>
    <h2>Receipts</h2>
    <table>
        <thead>
            <tr>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Date</th>
                <th>Category</th>
                <th>Account</th>
            </tr>
        </thead>
        <tbody>
            {% for receipt in receipt_list %}
            <tr>
                <td>{{ receipt.vendor }}</td>
                <td>{{ receipt.total }}</td>
                <td>{{ receipt.tax }}</td>
                <td>{{ receipt.date }}</td>
                <td>{{ receipt.category.name }}</td>
                <td>{{ receipt.account.name }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</main>

{% endblock content %}